CREATE TABLE PUBLIC.BRAND (
    ID INTEGER NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NAME)
);

CREATE TABLE PUBLIC.VEHICLE (
    ID INTEGER AUTO_INCREMENT,
    BRAND_ID INTEGER NOT NULL,
    MODEL VARCHAR(25) NOT NULL,
    RELEASED DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY(BRAND_ID) REFERENCES BRAND(ID)
);